/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedWellnessRouteImport } from './routes/_authenticated/wellness'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedBodyRouteImport } from './routes/_authenticated/body'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWellnessRoute = AuthenticatedWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBodyRoute = AuthenticatedBodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof AuthenticatedBodyRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/wellness': typeof AuthenticatedWellnessRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/body': typeof AuthenticatedBodyRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/wellness': typeof AuthenticatedWellnessRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/body': typeof AuthenticatedBodyRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/wellness': typeof AuthenticatedWellnessRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/body'
    | '/coach'
    | '/dashboard'
    | '/goals'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/tasks'
    | '/wellness'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/body'
    | '/coach'
    | '/dashboard'
    | '/goals'
    | '/nutrition'
    | '/onboarding'
    | '/profile'
    | '/tasks'
    | '/wellness'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/body'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/goals'
    | '/_authenticated/nutrition'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/tasks'
    | '/_authenticated/wellness'
    | '/_authenticated/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wellness': {
      id: '/_authenticated/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AuthenticatedWellnessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/body': {
      id: '/_authenticated/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof AuthenticatedBodyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBodyRoute: typeof AuthenticatedBodyRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedWellnessRoute: typeof AuthenticatedWellnessRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBodyRoute: AuthenticatedBodyRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedWellnessRoute: AuthenticatedWellnessRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
